### PR TITLE
version statement

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by scopatz** [comment]
Hopefully this is enough for #1

**Comment by Carreau** [comment]
Yes, I'm pretty sure that you will still get people attending who will not have Python 3 installed :-)

**Comment by scopatz** [comment]
I am sure - assuming this is accepted.

**Comment by Carreau** [comment]
If I am at Pycon (and this get accepted) I can give you  hand by being present and serving as a helper. Unless I have an IPython tutorial at the same time.

**Comment by scopatz** [comment]
Great! That would be awesome. I certainly don't want to be the only one presenting! Feel free to change the text at the bottom to reflect that too, if you want. I mostly copied it from my talk last year :)

**Pull request merged**
